### PR TITLE
Add Example_papers

### PR DESCRIPTION
**Pull request by Lauren-Blake**
This is a response to your email from this morning: 

In addition, it'd be great to get a sense of contemporary practices for differential gene expression analysis of time course experiments. Maybe a couple papers or two that are high impact and address more or less simliar question to ours... I'll look around as well.

### CODE REVIEW

**Comment by jhsiao999** [comment]
Nice job! 

P.S. Next time. Feel free to add the html to the homepage by editing analysis/index.Rmd. I'll add it to the homepage this time.

**Comment by Lauren-Blake** [comment]
Ok, cool. I will do that from now on.

**Comment by jhsiao999** [comment]
In addition, I changed the file names and replaced the underscores with dashes. I acquired this habit from when working on the singleCell project. Here's a discussion of the reason why.

https://blog.codinghorror.com/of-spaces-underscores-and-dashes/

**Comment by jhsiao999** [comment]
See here for the contributing guidelines that John put together:

https://github.com/jdblischak/singleCellSeq/blob/master/CONTRIBUTING.md

**Pull request merged**
